# 文件：docker-compose.yml
version: "3.9"
services:
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  backend:
    build: ./backend
    ports: ["8000:8000"]
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on: [redis]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  worker:
    build: ./backend
    command: ["celery", "-A", "tasks.celery", "worker", "--loglevel=info"]
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on: [redis]
